[tool.poetry]
name = "fexrd"
version = "v2021.1"
description = "Feature EXtractor for FFRI Dataset"
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/FFRI/FEXRD"
repository = "https://github.com/FFRI/FEXRD"
authors = ["Koh M. Nakagawa <ko.nakagawa@ffri.jp>"]
include = ["LICENSE"]
keywords = ["Malware", "FFRI Dataset", "Machine Learning"]

[tool.poetry.dependencies]
python = ">=3.6.8"
lief = {git = "https://github.com/kohnakagawa/LIEF.git", branch = "dev/ffri-dataset" }
pandas = "^1.0.4"
scikit-learn = "^0.23.2"
typer = "^0.3.2"
lightgbm = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
mypy = "^0.790"
flake8 = "^3.8.4"
isort = "^4.3.21"
black = "^20.8b1"
pytest-datadir = "^1.3.1"
flake8-black = "^0.2.1"
flake8-isort = "^4.0.0"
pre-commit = "^2.9.3"
mkdocs = "^1.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 80
