site_name: FEXRD Documentation
docs_dir: src
site_dir: ../docs

nav:
  - Introduction: 'index.md'
  - Motivation: 'motivation.md'
  - Basic Usage: 'basic_usage.md'
  - Advanced Usage: 'advanced_usage.md'
